export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: '/auth/login',
    REGISTER: '/user',
    LOGOUT: '/auth/logout',
    VERIFY_EMAIL: '/auth/verify-email',
    RESEND_OTP: '/auth/resend-otp',
    FORGOT_PASSWORD: '/auth/forgot-password',
    RESET_PASSWORD: '/auth/reset-password',
  },
  BOOKS: {
    CREATE_BOOK: '/books',
    MY_UPLOAD_BOOKS: '/books/my-upload-books',
    SEARCH_BOOKS: '/books/search',
    GET_BOOKS_PUBLIC: '/books',
    GET_BOOK: (bookId) => `/books/${bookId}`,
    UPDATE_BOOK: (bookId) => `/books/${bookId}`,
    DELETE_BOOK: (bookId) => `/books/${bookId}`,
    IMPORT_EPUB: (bookId) => `/books/${bookId}/import-epub`,
    MY_UNRATED_FINISHED_BOOKS: '/books/my-unrated-finished-books',
  },
  USER: {
    MY_INFO: '/user/myInfo',
    SEARCH: '/user/search',
    GET_BY_ID: (userId) => `/user/${userId}`,
    UPDATE: (userId) => `/user/${userId}`,
    DELETE: (userId) => `/user/${userId}`,
    UPGRADE_AUTHOR: '/user/upgrade-author',
  },
  CHAPTERS: {
    GET_CHAPTERS_BY_BOOK: (bookId, page = 0, size = 100) => `/chapters/book/${bookId}?page=${page}&size=${size}`,
    GET_CHAPTER: (chapterId) => `/chapters/${chapterId}`,
    UPDATE_CHAPTER: (chapterId) => `/chapters/${chapterId}`,
    DELETE_CHAPTER: (chapterId) => `/chapters/${chapterId}`,
    UNLOCK_CHAPTER: (chapterId) => `/chapters/${chapterId}/unlock`,
    BATCH_UPDATE: (bookId) => `/chapters/book/${bookId}/batch`,
    DELETE_ALL: (bookId) => `/chapters/book/${bookId}/all`,
    MY_UNLOCKS: '/api/chapters/my-unlocks',
    ADMIN_USER_UNLOCKS: (userId) => `/api/chapters/admin/user/${userId}/unlocks`,
  },
  CATEGORIES: {
    GET_ALL: '/categories',
    GET_LIST: '/categories/list',
    GET_ONE: (id) => `/categories/${id}`,
    CREATE: '/categories',
    UPDATE: (id) => `/categories/${id}`,
    DELETE: (id) => `/categories/${id}`,
  },
  AUTHORS: {
    GET_ALL: '/authors',
    GET_ONE: (id) => `/authors/${id}`,
    CREATE: '/authors',
    UPDATE: (id) => `/authors/${id}`,
    DELETE: (id) => `/authors/${id}`,
    SEARCH: '/authors/search',
  },
  PUBLISHERS: {
    GET_ALL: '/publishers',
    GET_ONE: (id) => `/publishers/${id}`,
    CREATE: '/publishers',
    UPDATE: (id) => `/publishers/${id}`,
    DELETE: (id) => `/publishers/${id}`,
    SEARCH: '/publishers/search',
  },
  RATINGS: {
    CREATE: (bookId) => `/ratings/book/${bookId}`,
    UPDATE: (ratingId) => `/ratings/${ratingId}`,
    DELETE: (ratingId) => `/ratings/${ratingId}`,
    GET_BY_BOOK: (bookId, page = 0, size = 10) => `/ratings/book/${bookId}?page=${page}&size=${size}`,
    MY_RATINGS: (page = 0, size = 10) => `/ratings/my-ratings?page=${page}&size=${size}`,
  },
  BOOKLISTS: {
    CREATE: '/booklists',
    GET_MY: '/booklists',
    GET_BY_ID: (id) => `/booklists/${id}`,
    UPDATE: (id) => `/booklists/${id}`,
    DELETE: (id) => `/booklists/${id}`,
    ADD_BOOK: (id, bookId) => `/booklists/${id}/books/${bookId}`,
    REMOVE_BOOK: (id, bookId) => `/booklists/${id}/books/${bookId}`,
    GET_BOOKS: (id, page = 0, size = 10) => `/booklists/${id}/books?page=${page}&size=${size}`,
  },
  READING_HISTORY: {
    SAVE: '/reading-history',
    GET_MY: (page = 0, size = 10) => `/reading-history?page=${page}&size=${size}`,
  },
  PLANS: {
    GET_ALL: '/api/plans',
  },
  SUBSCRIPTIONS: {
    GET_MY: '/api/subscriptions/my',
  },
  PAYMENT: {
    BUY_PACKAGE: '/api/payment/buy-package',
    ADMIN_USER_HISTORY: (userId) => `/api/payment/admin/user/${userId}`,
  },
  RECOMMENDATIONS: {
    GET_RECOMMENDATIONS: '/recommendations',
    TRAIN: '/recommendations/train',
  }
};
